import { Poppins } from "next/font/google";

import Navigation from "@/components/Navigation";
import "./styles/globals.css";

export const metadata = {
  title: "Amuse",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon/favicon.ico?v=4"],
    apple: ["/favicon/apple-touch-icon.png?v=4"],
    shortcut: ["/favicon/apple-touch-icon.png"],
  },
};

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-primary-800 antialiased ${poppins.className}`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
